Repository UCL/TDMS, pull requests merged in 2022-12, with the labels that each got.

#190 Test class for `array.h` classes
  tdms/tests/include/abstract_array_test_class.h
  tdms/tests/include/array_test_class.h
  tdms/tests/unit/array_tests/test_CollectionBase.cpp
  tdms/tests/unit/array_tests/test_ComplexAmplitudeSample.cpp
  tdms/tests/unit/array_tests/test_DTilde.cpp
  tdms/tests/unit/array_tests/test_DetectorSensitivityArrays.cpp
  tdms/tests/unit/array_tests/test_DispersiveMultiLayer.cpp
  tdms/tests/unit/array_tests/test_FieldSample.cpp
  tdms/tests/unit/array_tests/test_FrequencyVectors.cpp
  tdms/tests/unit/array_tests/test_IncidentField.cpp
  tdms/tests/unit/array_tests/test_Material.cpp
  tdms/tests/unit/array_tests/test_Matrix.cpp
  tdms/tests/unit/array_tests/test_Tensor3D.cpp
  tdms/tests/unit/array_tests/test_Vector.cpp
  tdms/tests/unit/array_tests/test_XYZTensor3D.cpp
  tdms/tests/unit/array_tests/test_XYZVectors.cpp
Labels: enhancement, testing, housekeeping

#149 Adding a `CellCoordinate` class to group `i,j,k`
  tdms/include/arrays.h
  tdms/include/cell_coordinate.h
  tdms/include/field.h
  tdms/src/fields/base.cpp
  tdms/src/fields/electric.cpp
  tdms/src/fields/magnetic.cpp
  tdms/src/iterator.cpp
  tdms/tests/unit/field_tests/test_Field_interpolation.cpp
Labels: housekeeping

#200 Rename phasorinc, add {C,D}Collection documentation, and `main()` → `main.cpp`
  .github/workflows/doxygen-gh-pages.yml
  README.md
  doc/developers.md
  tdms/CMakeLists.txt
  tdms/cmake/targets.cmake
  tdms/include/arrays.h
  tdms/include/mesh_base.h
  tdms/include/simulation_parameters.h
  tdms/src/argument_parser.cpp
  tdms/src/iterator.cpp
  tdms/src/main.cpp
  tdms/src/mesh_base.cpp
  tdms/src/openandorder.cpp
  tdms/src/simulation_parameters.cpp
Labels: documentation, housekeeping

#202 Update system tests
  tdms/tests/requirements.txt
  tdms/tests/system/read_config.py
  tdms/tests/system/test_arc01.py
  tdms/tests/system/test_arc02.py
  tdms/tests/system/test_arc03.py
  tdms/tests/system/test_arc08.py
  tdms/tests/system/test_arc09.py
  tdms/tests/system/test_arc10.py
  tdms/tests/system/test_arc12.py
  tdms/tests/system/test_arc13.py
  tdms/tests/system/test_fdtd.py
  tdms/tests/system/test_system.py
  tdms/tests/system/utils.py
Labels: technical, testing, housekeeping

#151 Replace cubic interpolation with Band-Limited Interpolation
  tdms/include/argument_parser.h
  tdms/include/arrays.h
  tdms/include/cell_coordinate.h
  tdms/include/field.h
  tdms/include/globals.h
  tdms/include/interpolate.h
  tdms/include/interpolation_methods.h
  tdms/include/iterator.h
  tdms/include/simulation_parameters.h
  tdms/matlabio/matlabio.h
  tdms/src/argument_parser.cpp
  tdms/src/fields/base.cpp
  tdms/src/fields/electric.cpp
  tdms/src/fields/magnetic.cpp
  tdms/src/interpolate.cpp
  tdms/src/interpolation_methods.cpp
  tdms/src/iterator.cpp
  tdms/src/main.cpp
  tdms/src/simulation_parameters.cpp
  tdms/tests/requirements.txt
  tdms/tests/system/read_config.py
  tdms/tests/system/test_arc01.py
  tdms/tests/system/test_arc02.py
  tdms/tests/system/test_arc03.py
  tdms/tests/system/test_arc08.py
  tdms/tests/system/test_arc09.py
  tdms/tests/system/test_arc10.py
  tdms/tests/system/test_arc12.py
  tdms/tests/system/test_arc13.py
  tdms/tests/system/test_fdtd.py
  tdms/tests/system/test_system.py
  tdms/tests/system/utils.py
  tdms/tests/unit/field_tests/test_Field_interpolation.cpp
  tdms/tests/unit/test_interpolation_determination.cpp
  tdms/tests/unit/test_interpolation_functions.cpp
Labels: enhancement, priority:1
