Repository UCL/TDMS, pull requests merged in 2022-09, with the labels that each got.

#79 Default to not building testing
  README.md
  tdms/CMakeLists.txt
Labels: technical

#83 Adds a spdlog logging
  tdms/CMakeLists.txt
  tdms/cmake/targets.cmake
  tdms/src/argument_parser.cpp
  tdms/src/openandorder.cpp
Labels: technical

#64 Refactor iterator [1/N]
  tdms/CMakeLists.txt
  tdms/include/fdtd_grid_initialiser.h
  tdms/include/field.h
  tdms/include/globals.h
  tdms/include/mat_io.h
  tdms/include/matrix_collection.h
  tdms/include/mesh_base.h
  tdms/include/numeric.h
  tdms/include/numerical_derivative.h
  tdms/include/simulation_parameters.h
  tdms/include/timer.h
  tdms/matlabio/matlabio.cpp
  tdms/matlabio/matlabio_globals.h
  tdms/matlabio/numeric.h
  tdms/src/electric_field.cpp
  tdms/src/fdtd_grid_initialiser.cpp
  tdms/src/interpolate.cpp
  tdms/src/interpolate_Hfield.cpp
  tdms/src/interpolation_methods.cpp
  tdms/src/iterator.cpp
  tdms/src/magnetic_field.cpp
  tdms/src/matrix_collection.cpp
  tdms/src/mesh_base.cpp
  tdms/src/numeric.cpp
  tdms/src/numerical_derivative.cpp
  tdms/src/openandorder.cpp
  tdms/src/simulation_parameters.cpp
  tdms/src/timer.cpp
  tdms/src/utils.cpp
  tdms/tests/unit/test_fields.cpp
  tdms/tests/unit/test_interpolate.cpp
  tdms/tests/unit/test_openandorder.cpp
Labels: review required

#96 Adding steady state tests.
  .gitignore
  doc/developers.md
  tdms/tests/README.md
  tdms/tests/system/test_arc08.py
Labels: testing

#98 Two more system tests.
  doc/developers.md
  tdms/tests/system/test_arc09.py
  tdms/tests/system/test_arc10.py
  tdms/tests/system/utils.py
Labels: testing

#94 Fix to steady state mode
  tdms/src/electric_field.cpp
  tdms/src/iterator.cpp
  tdms/tests/system/test_arc08.py
Labels: bug

#102 Fix the tests.
  .github/workflows/matlab_tests.yml
  .github/workflows/windows_tests.yml
  tdms/tests/system/test_cli.py
Labels: technical

#74 [Time-Domain] Interpolation functions for the H-field
  tdms/CMakeLists.txt
  tdms/include/interpolate_Efield.h
  tdms/include/interpolate_Hfield.h
  tdms/include/interpolation_methods.h
  tdms/src/interpolate_Efield.cpp
  tdms/src/interpolate_Hfield.cpp
  tdms/src/interpolation_methods.cpp
  tdms/tests/unit/test_interpolation_determination.cpp
  tdms/tests/unit/test_interpolation_functions.cpp
Labels: enhancement
