Repository UCL/TDMS, pull requests merged in 2023-02, with the labels that each got.

#228 Update spdlog version to v1.11.0.
  tdms/CMakeLists.txt
Labels: technical, review required, housekeeping

#221 Documentation follow-up for #215 plus minor doxygen fixes.
  doc/Doxyfile
  doc/developers.md
  tdms/include/cell_coordinate.h
  tdms/include/dimensions.h
  tdms/include/field.h
  tdms/include/globals.h
  tdms/include/input_matrices.h
  tdms/include/interpolation_methods.h
  tdms/include/mesh_base.h
  tdms/include/shapes.h
  tdms/include/simulation_manager/loop_timers.h
  tdms/include/simulation_manager/pstd_variables.h
  tdms/include/simulation_manager/simulation_manager.h
  tdms/include/simulation_parameters.h
  tdms/include/surface_phasors.h
  tdms/include/utils.h
  tdms/include/vertex_phasors.h
  tdms/src/matrix_collection.cpp
  tdms/tests/include/abstract_array_test_class.h
  tdms/tests/include/array_test_class.h
  tdms/tests/unit/field_tests/test_Field_interpolation.cpp
Labels: documentation, enhancement

#231 Add to Doxygen pages, and use doxygen as a CI check.
  .github/workflows/doxygen-gh-pages.yml
  README.md
  doc/Doxyfile
Labels: documentation, technical, review required, housekeeping

#224 #216 `iteratefdtd_matrix`: Updates for the main loop
  tdms/include/field.h
  tdms/include/simulation_manager/objects_from_infile.h
  tdms/include/simulation_manager/simulation_manager.h
  tdms/include/source.h
  tdms/src/simulation_manager/execute_simulation.cpp
  tdms/src/simulation_manager/simulation_manager.cpp
  tdms/src/simulation_manager/source_updates_pulsed.cpp
  tdms/src/simulation_manager/source_updates_steadystate.cpp
  tdms/src/source.cpp
Labels: enhancement, housekeeping
