Repository UCL/TDMS, pull requests merged in 2023-05, with the labels that each got.

#284 Add some configuration to codecov.
  .github/codecov.yml
Labels: technical, testing

#281 Infrastructure for removing `MATLAB`
  .github/workflows/ci.yml
  tdms/include/arrays.h
  tdms/include/cuboid.h
  tdms/include/hdf5_io/hdf5_base.h
  tdms/include/hdf5_io/hdf5_dimension.h
  tdms/include/hdf5_io/hdf5_reader.h
  tdms/include/input_matrices.h
  tdms/include/output_matrices/output_matrices.h
  tdms/include/shapes.h
  tdms/include/simulation_manager/objects_from_infile.h
  tdms/src/arrays.cpp
  tdms/src/hdf5_io/hdf5_base.cpp
  tdms/src/hdf5_io/hdf5_dimension.cpp
  tdms/src/hdf5_io/hdf5_reader.cpp
  tdms/src/input_matrices.cpp
  tdms/src/shapes.cpp
  tdms/src/simulation_manager/objects_from_infile.cpp
  tdms/tests/include/array_test_class.h
  tdms/tests/include/unit_test_utils.h
  tdms/tests/unit/array_tests/test_FrequencyVectors.cpp
  tdms/tests/unit/hdf5_and_tdms_objects/class_data.mat
  tdms/tests/unit/hdf5_and_tdms_objects/create_tdms_object_data.m
  tdms/tests/unit/hdf5_and_tdms_objects/test_hdf5_Cuboid.cpp
  tdms/tests/unit/hdf5_and_tdms_objects/test_hdf5_FrequencyVector.cpp
  tdms/tests/unit/hdf5_io_tests/structure_array.mat
  tdms/tests/unit/hdf5_io_tests/test_hdf5_dimension.cpp
  tdms/tests/unit/hdf5_io_tests/test_hdf5_reader.cpp
  tdms/tests/unit/matlab_benchmark_scripts/create_bad_tdms_object_data.m
  tdms/tests/unit/matlab_benchmark_scripts/create_structure_array.m
  tdms/tests/unit/matlab_benchmark_scripts/create_tdms_object_data.m
  tdms/tests/unit/matlab_benchmark_scripts/readme.md
  tdms/tests/unit/matlab_benchmark_scripts/setup_unit_tests.m
Labels: enhancement

#297 Remove (unused) using directive from header.
  tdms/tests/include/unit_test_utils.h
Labels: housekeeping

#262 Command line options moved to input file
  README.md
  doc/developers.md
  tdms/include/argument_parser.h
  tdms/include/field.h
  tdms/include/globals.h
  tdms/include/input_flags.h
  tdms/include/input_output_names.h
  tdms/include/interpolation_methods.h
  tdms/include/output_matrices/output_matrices.h
  tdms/include/simulation_manager/objects_from_infile.h
  tdms/include/simulation_manager/simulation_manager.h
  tdms/include/simulation_parameters.h
  tdms/src/argument_parser.cpp
  tdms/src/fields/electric.cpp
  tdms/src/fields/magnetic.cpp
  tdms/src/input_flags.cpp
  tdms/src/interpolation_methods.cpp
  tdms/src/main.cpp
  tdms/src/output_matrices/output_matrices.cpp
  tdms/src/simulation_manager/execute_simulation.cpp
  tdms/src/simulation_manager/execute_update_Ex_split.cpp
  tdms/src/simulation_manager/objects_from_infile.cpp
  tdms/src/simulation_manager/simulation_manager.cpp
  tdms/src/simulation_parameters.cpp
  tdms/tests/matlab/data/pstd_input_file_2D.m
  tdms/tests/matlab/data/pstd_input_file_3D.m
  tdms/tests/matlab/test_iteratefdtd_matrix.m
  tdms/tests/matlab/test_iteratefdtd_matrix_source_configurations.m
  tdms/tests/matlab/utils/set_use_pstd.m
  tdms/tests/matlab/utils/set_usecd.m
  tdms/tests/system/config_files/config_01.yaml
  tdms/tests/system/config_files/config_02.yaml
  tdms/tests/system/config_files/config_03.yaml
  tdms/tests/system/config_files/config_08.yaml
  tdms/tests/system/config_files/config_09.yaml
  tdms/tests/system/config_files/config_10.yaml
  tdms/tests/system/config_files/config_12.yaml
  tdms/tests/system/config_files/config_13.yaml
  tdms/tests/system/config_files/config_example_fdtd.yaml
  tdms/tests/system/data/input_generation/input_files/input_file_01.m
  tdms/tests/system/data/input_generation/input_files/input_file_02.m
  tdms/tests/system/data/input_generation/input_files/input_file_03.m
  tdms/tests/system/data/input_generation/input_files/input_file_08.m
  tdms/tests/system/data/input_generation/input_files/input_file_09.m
  tdms/tests/system/data/input_generation/input_files/input_file_10.m
  tdms/tests/system/data/input_generation/input_files/input_file_12.m
  tdms/tests/system/data/input_generation/input_files/input_file_13.m
  tdms/tests/system/data/input_generation/input_files/input_file_example_fdtd.m
  tdms/tests/system/data/input_generation/matfile_option_edit.py
  tdms/tests/system/data/input_generation/matlab/iteratefdtd_matrix.m
  tdms/tests/system/read_config.py
  tdms/tests/system/run_system_test.py
  tdms/tests/system/test_regen.py
  tdms/tests/system/test_system.py
  tdms/tests/unit/field_tests/test_Field_interpolation.cpp
  tdms/tests/unit/matlab_benchmark_scripts/readme.md
  tdms/tests/unit/test_BLi_vs_cubic_interpolation.cpp
  tdms/tests/unit/test_argument_parser.cpp
  tdms/tests/unit/test_interpolation_determination.cpp
  tdms/tests/unit/test_interpolation_functions.cpp
Labels: enhancement, priority:1, review required, subtask

#300 Fallback to v1 if no tag provided (or no git repo)
  tdms/include/globals.h
Labels: documentation, enhancement, ux

#306 CodeCov setup flags as message
  tdms/CMakeLists.txt
Labels: documentation, enhancement

#305 Turn off coverage reporting in MacOS
  .github/workflows/ci.yml
Labels: technical, testing, subtask

#304 Add dependence on `libhdf5` and basic implementation class structure.
  .github/workflows/ci.yml
  README.md
  tdms/CMakeLists.txt
  tdms/cmake/targets.cmake
  tdms/include/hdf5_io.h
  tdms/src/hdf5_io.cpp
  tdms/tests/unit/test_hdf5_io.cpp
Labels: enhancement, review required

#308 Add Zenodo DOI to README.md and CITATION.cff.
  CITATION.cff
  README.md
Labels: documentation, housekeeping

#310 Test-driven reading and writing basic datatypes to HDF5.
  README.md
  doc/assets/matlab-file-settings.png
  tdms/CMakeLists.txt
  tdms/include/arrays.h
  tdms/include/fdtd_grid_initialiser.h
  tdms/include/hdf5_io.h
  tdms/src/hdf5_io.cpp
  tdms/tests/unit/small_fdtdgrid.mat
  tdms/tests/unit/test_hdf5_io.cpp
Labels: enhancement

#311 Handle structs (except with complex data, that's nasty)
  tdms/include/hdf5_io.h
  tdms/tests/unit/small_fdtdgrid.mat
  tdms/tests/unit/structure_array.mat
  tdms/tests/unit/test_hdf5_io.cpp
Labels: enhancement, review required

#312 `HDF5` file structure reorganisation, and `InterfaceComponent` readability
  tdms/include/hdf5_io.h
  tdms/include/hdf5_io/hdf5_base.h
  tdms/include/hdf5_io/hdf5_reader.h
  tdms/include/hdf5_io/hdf5_writer.h
  tdms/include/interface.h
  tdms/src/hdf5_io/hdf5_base.cpp
  tdms/src/hdf5_io/hdf5_reader.cpp
  tdms/src/hdf5_io/hdf5_writer.cpp
  tdms/tests/include/unit_test_utils.h
  tdms/tests/unit/hdf5_and_tdms_objects/class_data.mat
  tdms/tests/unit/hdf5_and_tdms_objects/create_tdms_object_data.m
  tdms/tests/unit/hdf5_and_tdms_objects/test_hdf5_InterfaceComponent.cpp
  tdms/tests/unit/hdf5_and_tdms_objects/test_hdf5_Matrix.cpp
  tdms/tests/unit/hdf5_io_tests/create_structure_array.m
  tdms/tests/unit/hdf5_io_tests/structure_array.mat
  tdms/tests/unit/hdf5_io_tests/test_hdf5_io.cpp
  tdms/tests/unit/hdf5_io_tests/test_hdf5_reader.cpp
Labels: enhancement, review required

#319 Install `libtdms_lib.so` correctly
  tdms/CMakeLists.txt
Labels: bug, technical, ux, housekeeping

#323 Add troubleshooting instructions to README.md
  README.md
Labels: documentation, review required, opinions wanted

#314 Infrastructure for removing `MATLAB`
  .github/workflows/ci.yml
  tdms/include/arrays.h
  tdms/include/arrays/cuboid.h
  tdms/include/hdf5_io/hdf5_base.h
  tdms/include/hdf5_io/hdf5_dimension.h
  tdms/include/hdf5_io/hdf5_reader.h
  tdms/include/input_matrices.h
  tdms/include/interface.h
  tdms/include/output_matrices/output_matrices.h
  tdms/include/shapes.h
  tdms/include/simulation_manager/objects_from_infile.h
  tdms/src/arrays.cpp
  tdms/src/hdf5_io/hdf5_base.cpp
  tdms/src/hdf5_io/hdf5_dimension.cpp
  tdms/src/hdf5_io/hdf5_reader.cpp
  tdms/src/input_matrices.cpp
  tdms/src/shapes.cpp
  tdms/src/simulation_manager/objects_from_infile.cpp
  tdms/tests/include/array_test_class.h
  tdms/tests/include/unit_test_utils.h
  tdms/tests/unit/array_tests/test_FrequencyVectors.cpp
  tdms/tests/unit/benchmark_scripts/unit_test_data/hdf5_test_file.hdf5
  tdms/tests/unit/hdf5_and_tdms_objects/test_hdf5_Cuboid.cpp
  tdms/tests/unit/hdf5_and_tdms_objects/test_hdf5_FrequencyVector.cpp
  tdms/tests/unit/hdf5_io_tests/test_hdf5_dimension.cpp
  tdms/tests/unit/hdf5_io_tests/test_hdf5_io.cpp
  tdms/tests/unit/hdf5_io_tests/test_hdf5_reader.cpp
  tdms/tests/unit/matlab_benchmark_scripts/create_bad_tdms_object_data.m
  tdms/tests/unit/matlab_benchmark_scripts/create_structure_array.m
  tdms/tests/unit/matlab_benchmark_scripts/create_tdms_object_data.m
  tdms/tests/unit/matlab_benchmark_scripts/readme.md
  tdms/tests/unit/matlab_benchmark_scripts/setup_unit_tests.m
Labels: enhancement, review required, housekeeping

#318 Add a smoke test to CI.
  .github/workflows/ci.yml
Labels: testing, housekeeping
